const nodemailer = require("nodemailer");

// SMTP Configuration
const createTransporter = () => {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST || "mail.smtp2go.com",
    port: parseInt(process.env.SMTP_PORT) || 2525,
    secure: process.env.SMTP_SECURE === "true",
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
    debug: process.env.NODE_ENV === "development",
  });
};

// Email Templates
const createAdminNotificationEmail = (contactData) => {
  const { name, email, phone, eventType, message, createdAt } = contactData;

  return {
    subject: `🔔 New Contact Form Submission - ${name}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
        <div style="background: linear-gradient(135deg, #d97706 0%, #ea580c 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px;">📧 New Contact Form Submission</h1>
          <p style="color: white; margin: 10px 0 0 0; opacity: 0.9;">Marigold Catering + Events</p>
        </div>
        
        <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <div style="margin-bottom: 25px;">
            <h2 style="color: #333; margin-bottom: 20px; border-bottom: 2px solid #d97706; padding-bottom: 10px;">Contact Details</h2>
            
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555; width: 30%;">👤 Name:</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; color: #333;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">✉️ Email:</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; color: #333;">
                  <a href="mailto:${email}" style="color: #d97706; text-decoration: none;">${email}</a>
                </td>
              </tr>
              ${
                phone
                  ? `
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">📱 Phone:</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; color: #333;">
                  <a href="tel:${phone}" style="color: #d97706; text-decoration: none;">${phone}</a>
                </td>
              </tr>
              `
                  : ""
              }
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">🎉 Event Type:</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; color: #333;">
                  <span style="background: #d97706; color: white; padding: 4px 12px; border-radius: 15px; text-transform: capitalize;">${eventType}</span>
                </td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">📅 Submitted:</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #eee; color: #333;">${new Date(
                  createdAt
                ).toLocaleString()}</td>
              </tr>
            </table>
          </div>

          <div style="margin-bottom: 25px;">
            <h3 style="color: #333; margin-bottom: 15px;">💬 Message:</h3>
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #d97706;">
              <p style="margin: 0; line-height: 1.6; color: #555; white-space: pre-wrap;">${message}</p>
            </div>
          </div>

          <div style="text-align: center; margin-top: 30px;">
            <a href="mailto:${email}" style="background: #d97706; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; margin-right: 10px;">📧 Reply to ${name}</a>
            ${
              phone
                ? `<a href="tel:${phone}" style="background: #059669; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">📱 Call ${name}</a>`
                : ""
            }
          </div>
        </div>
        
        <div style="text-align: center; margin-top: 20px; color: #666; font-size: 12px;">
          <p>This email was automatically generated by your website contact form.</p>
          <p>© ${new Date().getFullYear()} Marigold Catering + Events</p>
        </div>
      </div>
    `,
    text: `
New Contact Form Submission

Name: ${name}
Email: ${email}
${phone ? `Phone: ${phone}` : ""}
Event Type: ${eventType}
Submitted: ${new Date(createdAt).toLocaleString()}

Message:
${message}

---
Reply to this inquiry: mailto:${email}
${phone ? `Call: tel:${phone}` : ""}
    `.trim(),
  };
};

const createThankYouEmail = (contactData) => {
  const { name, eventType } = contactData;

  return {
    subject: `Thank you for contacting Marigold Catering + Events! 🌼`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
        <div style="background: linear-gradient(135deg, #d97706 0%, #ea580c 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 28px;">🌼 Thank You!</h1>
          <p style="color: white; margin: 10px 0 0 0; font-size: 18px;">Marigold Catering + Events</p>
        </div>
        
        <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <div style="margin-bottom: 25px;">
            <h2 style="color: #333; margin-bottom: 20px;">Dear ${name},</h2>
            
            <p style="color: #555; line-height: 1.6; margin-bottom: 20px;">
              Thank you for reaching out to us about your upcoming <strong>${eventType}</strong> event! We're thrilled that you're considering Marigold Catering + Events to help make your special occasion memorable.
            </p>
            
            <p style="color: #555; line-height: 1.6; margin-bottom: 20px;">
              We've received your inquiry and our team is already reviewing the details. Here's what happens next:
            </p>
            
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
              <h3 style="color: #d97706; margin-top: 0; margin-bottom: 15px;">📋 Next Steps:</h3>
              <ul style="color: #555; margin: 0; padding-left: 20px;">
                <li style="margin-bottom: 8px;">Our event planning team will review your requirements</li>
                <li style="margin-bottom: 8px;">We'll reach out within <strong>24-48 hours</strong> to discuss your vision</li>
                <li style="margin-bottom: 8px;">Schedule a consultation to plan your perfect event</li>
                <li style="margin-bottom: 8px;">Receive a customized proposal tailored to your needs</li>
              </ul>
            </div>
            
            <div style="background: linear-gradient(135deg, #f3f4f6 0%, #e5e7eb 100%); padding: 20px; border-radius: 8px; margin-bottom: 25px;">
              <h3 style="color: #333; margin-top: 0; margin-bottom: 15px;">✨ Why Choose Marigold?</h3>
              <ul style="color: #555; margin: 0; padding-left: 20px;">
                <li style="margin-bottom: 8px;">🍽️ <strong>Exceptional Cuisine:</strong> Crafted by our expert culinary team</li>
                <li style="margin-bottom: 8px;">👥 <strong>Professional Service:</strong> Experienced staff dedicated to your event's success</li>
                <li style="margin-bottom: 8px;">🎨 <strong>Custom Planning:</strong> Tailored to your unique vision and style</li>
                <li style="margin-bottom: 8px;">❤️ <strong>Personal Touch:</strong> We treat every event as if it were our own</li>
              </ul>
            </div>
            
            <p style="color: #555; line-height: 1.6; margin-bottom: 25px;">
              In the meantime, feel free to browse our <a href="https://marigoldcatering.com/venues" style="color: #d97706; text-decoration: none;">venue portfolio</a> or check out our <a href="https://marigoldcatering.com/gallery" style="color: #d97706; text-decoration: none;">gallery</a> to see examples of our work.
            </p>
            
            <div style="text-align: center; margin-bottom: 25px;">
              <a href="https://marigoldcatering.com/contact" style="background: #d97706; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; margin: 5px;">📞 Contact Us</a>
              <a href="https://marigoldcatering.com/services" style="background: #059669; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; margin: 5px;">🎉 View Services</a>
            </div>
          </div>

          <div style="border-top: 2px solid #e5e7eb; padding-top: 20px; margin-top: 25px;">
            <p style="color: #666; font-size: 14px; margin-bottom: 15px;">
              <strong>Questions?</strong> Don't hesitate to reach out:
            </p>
            <p style="color: #666; font-size: 14px; margin: 5px 0;">
              📧 Email: <a href="mailto:inquiries@marigoldcatering.com" style="color: #d97706; text-decoration: none;">inquiries@marigoldcatering.com</a>
            </p>
            <p style="color: #666; font-size: 14px; margin: 5px 0;">
              🌐 Website: <a href="https://marigoldcatering.com" style="color: #d97706; text-decoration: none;">marigoldcatering.com</a>
            </p>
          </div>
        </div>
        
        <div style="text-align: center; margin-top: 20px; color: #666; font-size: 12px;">
          <p>We can't wait to help you create an unforgettable event!</p>
          <p>© ${new Date().getFullYear()} Marigold Catering + Events • Cleveland, Ohio</p>
        </div>
      </div>
    `,
    text: `
Dear ${name},

Thank you for reaching out to us about your upcoming ${eventType} event! We're thrilled that you're considering Marigold Catering + Events to help make your special occasion memorable.

We've received your inquiry and our team is already reviewing the details. Here's what happens next:

📋 Next Steps:
• Our event planning team will review your requirements
• We'll reach out within 24-48 hours to discuss your vision
• Schedule a consultation to plan your perfect event
• Receive a customized proposal tailored to your needs

✨ Why Choose Marigold?
• 🍽️ Exceptional Cuisine: Crafted by our expert culinary team
• 👥 Professional Service: Experienced staff dedicated to your event's success
• 🎨 Custom Planning: Tailored to your unique vision and style
• ❤️ Personal Touch: We treat every event as if it were our own

In the meantime, feel free to browse our venue portfolio or check out our gallery at https://marigoldcatering.com

Questions? Don't hesitate to reach out:
📧 Email: inquiries@marigoldcatering.com
🌐 Website: marigoldcatering.com

We can't wait to help you create an unforgettable event!

© ${new Date().getFullYear()} Marigold Catering + Events • Cleveland, Ohio
    `.trim(),
  };
};

// Email Sending Functions
const sendAdminNotification = async (contactData) => {
  const transporter = createTransporter();
  const adminEmails = process.env.ADMIN_EMAIL_ADDRESSES?.split(",") || [
    "najarkamran212@gmail.com",
    "inquiries@marigoldcatering.com",
  ];

  const emailTemplate = createAdminNotificationEmail(contactData);

  const mailOptions = {
    from: `${process.env.SMTP_FROM_NAME || "Marigold Catering"} <${
      process.env.SMTP_FROM_EMAIL
    }>`,
    to: adminEmails,
    subject: emailTemplate.subject,
    html: emailTemplate.html,
    text: emailTemplate.text,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("Admin notification sent:", info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error("Failed to send admin notification:", error);
    throw error;
  }
};

const sendThankYouEmail = async (contactData) => {
  const transporter = createTransporter();
  const emailTemplate = createThankYouEmail(contactData);

  const mailOptions = {
    from: `${process.env.SMTP_FROM_NAME || "Marigold Catering"} <${
      process.env.SMTP_FROM_EMAIL
    }>`,
    to: contactData.email,
    subject: emailTemplate.subject,
    html: emailTemplate.html,
    text: emailTemplate.text,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("Thank you email sent:", info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error("Failed to send thank you email:", error);
    throw error;
  }
};

const sendContactFormEmails = async (contactData) => {
  const results = {
    adminNotification: null,
    thankYou: null,
  };

  // Send admin notification
  try {
    results.adminNotification = await sendAdminNotification(contactData);
  } catch (error) {
    console.error("Admin notification failed:", error);
    results.adminNotification = { success: false, error: error.message };
  }

  // Send thank you email to submitter
  try {
    results.thankYou = await sendThankYouEmail(contactData);
  } catch (error) {
    console.error("Thank you email failed:", error);
    results.thankYou = { success: false, error: error.message };
  }

  return results;
};

module.exports = {
  sendContactFormEmails,
  sendAdminNotification,
  sendThankYouEmail,
};
